echo // This file is automatically generated or updated^, please don't edit it.> %1\Version.h 
echo #pragma once>> %1\Version.h 
for /F %%i in ('git rev-parse --short HEAD') do ( set commitid=%%i)
:: for /F %%i in ('git rev-parse HEAD') do ( set commitid=%%i)
echo #define GIT_COMMIT_ID %commitid%>> %1\Version.h 
:: git rev-parse HEAD >> %1\Version.h
exit